sudo: required

language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"

services:
  - docker

before_script:
  - echo 'DOCKER_OPTS="--storage-driver=devicemapper"' | sudo tee --append /etc/default/docker >/dev/null && service docker restart

script: npm run test:parallel
